### ISSUE TITLE
Url validator should consider www.test.com as valid

### ISSUE THREAD

**Issue by ducalai** [rsaenen/ngx-custom-validators#16]
Url validator consider www.test.com as invalid, because not starting with http://, https://, or ftp://.

It should be less restrictive and should consider a url starting with www as valid.

What do you think?

**Comment by rsaenen** [comment]
AFAIK, an url should begin with the protocol.

Less restrictive would assume that the protocol is https by most of modern navigator.

www.test.com is an url because it's a sub domain of test.com. I guess a regex which allows test.com is not enough strong...

Why not use a pipe to add the protocol if needed ?

**Comment by ducalai** [comment]
Ok.
I'll go around by using a pipe.
Thanks for your reply
